AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: Marketplace
Parameters:
  IdentityNameParameter:
    Type: String
Resources:
  website:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src/index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 3
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter
      Environment:
          Variables:
              BUCKET: value
      Events:
        ## TODO: How to define optional parameter so we only get one route?
        ApiEventRoot:
          Type: Api
          Properties:
            Path: /
            Method: get
        ApiEventParam:
          Type: Api
          Properties:
            Path: /{route}
            Method: get
